

services:
  # Redis service as the message broker
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  # Flask web service
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:5000 'app:create_app()'
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DATABASE_URL=postgresql://postgres.mcwdnxxaxhwldthougho:SocialVIsta123@aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres

  # Celery worker service
  celery_worker:
    build: .
    command: celery -A celery_worker.celery worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DATABASE_URL=postgresql://postgres.mcwdnxxaxhwldthougho:SocialVIsta123@aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres
